# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy askia-lite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          # npm run test --passWithNoTests --if-present
          
      - name : deploy in github page
        run : |
          git config --global user.email secret.PUBLISH_USERNAME
          git config --global user.name secret.PUBLISH_USERNAME
          GIT_USER=secret.PUBLISH_USERNAME npm run deploy
          
